language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/avo-shopper;

node_js:  
  - 12

before_script:
  - psql -c 'create database  "avo-shopper";' -U postgres
  - psql -U postgres -d "avo-shopper" -a -f ./sql/tables.sql
  - psql -U postgres -d "avo-shopper" -a -f data.sql

services:
  - postgresql